Problem Statement: 

To make a suitable machine learning algorithm to predict if the mushroom is
edible or poisonous (e or p) using the given dataset. 
(Along with other ML algorithms, Naïve Bayes’ Classifier should be applied)
Also, if some data pre-processing is necessary do that as well.


In [1]:
#importing libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
#reading data

dt=pd.read_csv("mushrooms.csv")
dt.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [4]:
#label encoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for column in dt.columns:
    dt[column]=le.fit_transform(dt[column])

In [5]:
dt.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [6]:
#veil type not contributing so we can remove it

dt['veil-type']


0       0
1       0
2       0
3       0
4       0
       ..
8119    0
8120    0
8121    0
8122    0
8123    0
Name: veil-type, Length: 8124, dtype: int32

In [7]:
dt=dt.drop(['veil-type'],axis=1)

In [8]:
# Split the dataset

x=dt.drop(['class'],axis=1)
y=dt['class']

In [9]:
#Standardization

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=scaler.fit_transform(x)
x=pd.DataFrame(x)
x.describe()

0             1             2             3             4   \
count  8.124000e+03  8.124000e+03  8.124000e+03  8.124000e+03  8.124000e+03   
mean  -5.423612e-15  4.217659e-17  4.423065e-15 -1.797258e-14 -3.590486e-15   
std    1.000062e+00  1.000062e+00  1.000062e+00  1.000062e+00  1.000062e+00   
min   -2.087047e+00 -1.486157e+00 -1.769549e+00 -8.432296e-01 -1.970316e+00   
25%   -8.403434e-01 -1.486157e+00 -5.910746e-01 -8.432296e-01 -1.019565e+00   
50%   -2.169915e-01  1.401279e-01 -1.982498e-01 -8.432296e-01  4.065620e-01   
75%    1.029712e+00  9.532704e-01  1.373049e+00  1.185917e+00  4.065620e-01   
max    1.029712e+00  9.532704e-01  1.765874e+00  1.185917e+00  1.832689e+00   

                 5             6             7             8             9   \
count  8.124000e+03  8.124000e+03  8.124000e+03  8.124000e+03  8.124000e+03   
mean  -2.478055e-14  8.422977e-15  8.636999e-15  1.302651e-14 -6.287000e-15   
std    1.000062e+00  1.000062e+00  1.000062e+00  1.000062e+00  1.000062e+00   
min   -6.138869e+00 -4.388636e-01 -6.690383e-01 -1.358896e+00 -1.144806e+00   
25%    1.628965e-01 -4.388636e-01 -6.690383e-01 -7.939470e-01 -1.144806e+00   
50%    1.628965e-01 -4.388636e-01 -6.690383e-01  5.347685e-02  8.735106e-01   
75%    1.628965e-01 -4.388636e-01  1.494683e+00  6.184261e-01  8.735106e-01   
max    1.628965e-01  2.278612e+00  1.494683e+00  1.748325e+00  8.735106e-01   

       ...            11            12            13            14  \
count  ...  8.124000e+03  8.124000e+03  8.124000e+03  8.124000e+03   
mean   ...  5.016557e-15  1.023102e-15  1.695586e-14 -1.065692e-14   
std    ...  1.000062e+00  1.000062e+00  1.000062e+00  1.000062e+00   
min    ... -2.534652e+00 -2.372490e+00 -3.058611e+00 -3.038361e+00   
25%    ... -9.254372e-01 -8.930529e-01  9.657680e-02  1.076554e-01   
50%    ...  6.837777e-01  5.863847e-01  6.224414e-01  6.319914e-01   
75%    ...  6.837777e-01  5.863847e-01  6.224414e-01  6.319914e-01   
max    ...  2.292993e+00  2.065822e+00  1.148306e+00  1.156327e+00   

                 15            16            17            18            19  \
count  8.124000e+03  8.124000e+03  8.124000e+03  8.124000e+03  8.124000e+03   
mean   2.558990e-14  2.290006e-16 -2.067585e-14  5.804445e-14 -6.046588e-15   
std    1.000062e+00  1.000062e+00  1.000062e+00  1.000062e+00  1.000062e+00   
min   -8.100146e+00 -3.945519e+00 -1.272216e+00 -1.509643e+00 -2.910546e+00   
25%    1.420366e-01 -2.561317e-01 -1.272216e+00 -6.701949e-01 -5.143892e-01   
50%    1.420366e-01 -2.561317e-01 -1.620674e-01 -2.504706e-01  2.843298e-01   
75%    1.420366e-01 -2.561317e-01  9.480809e-01  1.428426e+00  2.843298e-01   
max    4.263128e+00  3.433255e+00  9.480809e-01  1.848151e+00  1.083049e+00   

                 20  
count  8.124000e+03  
mean   9.402621e-15  
std    1.000062e+00  
min   -8.771691e-01  
25%   -8.771691e-01  
50%   -2.957297e-01  
75%    2.857098e-01  
max    2.611468e+00  

[8 rows x 21 columns]

In [10]:
#Normalization

from sklearn.preprocessing import Normalizer
norm=Normalizer()
x=norm.fit_transform(x)
x=pd.DataFrame(x)
x.head()

0         1         2         3         4         5         6   \
0  0.244678  0.033297 -0.047108  0.281795  0.209564  0.038707 -0.104282   
1  0.252143  0.034313  0.432405  0.290392 -0.482466  0.039888 -0.107463   
2 -0.525568  0.035288  0.345766  0.298642 -0.137040  0.041021 -0.110516   
3  0.228002  0.211076  0.304025  0.262589  0.195281  0.036069 -0.097175   
4  0.210695  0.028672 -0.120943 -0.172538  0.083189  0.033331  0.466239   

         7         8         9   ...        11        12        13        14  \
0  0.355163 -0.054414 -0.272026  ...  0.162478  0.139335  0.147903  0.150172   
1 -0.163826 -0.056074 -0.280325  ...  0.167435  0.143586  0.152416  0.154754   
2 -0.168480  0.013467 -0.288289  ...  0.172191  0.147665  0.156745  0.159150   
3  0.330957  0.011841 -0.253487  ...  0.151404  0.129839  0.137823  0.139938   
4 -0.136895 -0.046856  0.178734  ...  0.139911  0.119983  0.127361  0.129315   

         15        16        17        18        19        20  
0  0.033750 -0.060861  0.225281 -0.159250 -0.122228  0.482371  
1  0.034780 -0.062718  0.232154 -0.061332 -0.321537 -0.072415  
2  0.035768 -0.064500  0.238749 -0.063074 -0.330672  0.218369  
3  0.031450 -0.056714  0.209927 -0.148397 -0.113898  0.449495  
4  0.029063 -0.052408 -0.260315 -0.051250 -0.595542 -0.060511  

[5 rows x 21 columns]

In [11]:
#Splitting data into train and test data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

# Classsification Models

# LOGISTIC REGRESSION

In [12]:
#LOGISTIC REGRESSION

from sklearn.linear_model import LogisticRegression
logit_model=LogisticRegression()
logit_model.fit(x_train,y_train)
y_pred_lr=logit_model.predict(x_test)

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,classification_report

In [14]:

print("Logistic regression report: \n\n", classification_report(y_test, y_pred_lr))

Logistic regression report: 

               precision    recall  f1-score   support

           0       0.94      0.95      0.95      1040
           1       0.95      0.94      0.95       991

    accuracy                           0.95      2031
   macro avg       0.95      0.95      0.95      2031
weighted avg       0.95      0.95      0.95      2031



In [15]:
 confusion_matrix(y_test, y_pred_lr)
    

array([[990,  50],
       [ 58, 933]], dtype=int64)

# Support Vector Matrix

In [16]:
#Support Vector Matrix

from sklearn.svm import SVC
svm = SVC(random_state=42,kernel='linear')
svm.fit(x_train, y_train)
y_pred_svm=svm.predict(x_test)

In [17]:
print("SVM Classification report: \n\n", classification_report(y_test, y_pred_svm))

SVM Classification report: 

               precision    recall  f1-score   support

           0       0.97      0.96      0.96      1040
           1       0.95      0.97      0.96       991

    accuracy                           0.96      2031
   macro avg       0.96      0.96      0.96      2031
weighted avg       0.96      0.96      0.96      2031



In [18]:
confusion_matrix(y_test, y_pred_svm)

array([[994,  46],
       [ 33, 958]], dtype=int64)

# Decision Tree

In [19]:
#Decision Tree

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
y_pred_dt=dt.predict(x_test)

In [20]:
print("Decision Tree Classification Report: \n\n", classification_report(y_test, y_pred_dt))


Decision Tree Classification Report: 

               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1040
           1       1.00      1.00      1.00       991

    accuracy                           1.00      2031
   macro avg       1.00      1.00      1.00      2031
weighted avg       1.00      1.00      1.00      2031



In [21]:
confusion_matrix(y_test,y_pred_dt)

array([[1037,    3],
       [   1,  990]], dtype=int64)

# Random Forest

In [22]:
#Random Forest

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(x_train, y_train)
y_pred_rf=rf.predict(x_test)

In [23]:
print("Random forest Classification report: \n\n", classification_report(y_test, y_pred_rf))

Random forest Classification report: 

               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1040
           1       1.00      1.00      1.00       991

    accuracy                           1.00      2031
   macro avg       1.00      1.00      1.00      2031
weighted avg       1.00      1.00      1.00      2031



In [24]:
confusion_matrix(y_test,y_pred_rf)

array([[1040,    0],
       [   0,  991]], dtype=int64)

# Naive Bayes Classification

In [25]:
#Naive Bayes Classification

from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)
y_pred_Gu=classifier.predict(x_test)
y_pred_Gu

array([0, 1, 1, ..., 0, 0, 1])

In [26]:
confusion_matrix(y_test,y_pred_Gu)

array([[985,  55],
       [ 71, 920]], dtype=int64)

In [27]:
accuracy_score(y_test,y_pred_Gu)


0.9379615952732644

Out of all the classification models, Decision Tree and Random Forest Model give the highest accuracy